name: vec
dependencies:
- openssl=1.0.2d=0
- pip
- pip:
  - "ipython[notebook]<4"
  - toolz
  - snakeviz
  #- pygraphviz
  - fuzzywuzzy
  - autograd
  - voluptuous
  - pytest
- python=3.5
- spacy
- nltk
- pandas
- numexpr
- gensim
- seaborn
- joblib
- statsmodels
- scikit-learn
- pygments
#- mkl

- numba
- line_profiler



